name: Test

on:
  push:
    branches:
      - master
      - v*
    paths:
      - "**/*.go"
      - "go.mod"
      - "go.sum"
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - "**/*.go"
      - "go.mod"
      - "go.sum"

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
        include:
          - os: windows-latest
            protoc: win64
          - os: ubuntu-latest
            protoc: linux-x86_64
          - os: macos-latest
            protoc: osx-x86_64
          
    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: ^1.16

      - name: Checkout codebase5
        uses: actions/checkout@v2
      - name: Generate files
        shell: bash
        run: |
          PB_REL="https://github.com/protocolbuffers/protobuf/releases"
          curl -LO $PB_REL/download/v3.12.1/protoc-3.12.1-${{ matrix.protoc }}.zip
          unzip protoc-3.12.1-${{ matrix.protoc }}.zip
          export PATH=$PATH:$(pwd)/bin:~/go/bin
          go generate proto.go

      - name: Test
        run: go test -v -timeout 1h ./...
